### ISSUE TITLE
Отсутствует инструкция по запуску сервера в README.md

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-4-forum#12]
Мы с Александром Вячеславовичем не смогли запустить форум на машине (NodeJS v6.10.0, Windows 10). Напишите, пожалуйста, инструкцию по запуску, иначе вся группа будет не аттестована (кстати, других тоже касается).

**Comment by NinaLeven** [comment]
В настоящий момент мы заканчиваем работу над проектом, как только он будет готов - я смогу написать инструкции по его запуску и работе с форумом.
